### ISSUE TITLE
弹幕渲染窗口无法点透

### ISSUE THREAD

**Issue by benpigchu** [mulab/CamusKit.Danmaku#5]
这是一个很大的问题，但是既然既然我们选择了electron，我们就只能等待electron提供相应的API之后（见 electron/electron#1335 与 electron/electron#2864 ）才能解决这个问题。

**Comment by Dafrok** [comment]
https://github.com/Dafrok/desktop-barrage

太巧了 我和你们做同一个project遇到同一个问题看到同一个issue
目前是用每条弹幕新开browser-window的方法解决的

**Comment by benpigchu** [comment]
@Dafrok 【我们觉得开太多browser-window对性能影响太大，毕竟这是一条弹幕数据和一个窗口的区别】

**Comment by Dafrok** [comment]
性能确实会有一些损失 但实践证明在主进程里用定时器控制browse-window流畅的很

**Comment by benpigchu** [comment]
@Dafrok 【还有一个问题：同屏弹幕数量多的时候还是没办法点透（】

**Comment by Dafrok** [comment]
嗯 所以更改了一下用户体验 左键关闭右键打开（

**Comment by benpigchu** [comment]
【 electron/electron#5910 实现了跨平台的单窗口鼠标点透API（只能全部点透，不能部分点透），electron v1.2.2中已经包含这一API，不能点透的问题也就可以解决了。之前版本中也有此API，但仅支持Mac OS】
